/* POKEMON CANNOT BE INSERTED WITH 5 MOVES;
THIS IS ALSO ENFORCED AT THE LEVEL OF THE APPLICATION
BECAUSE WE WILL ONLY LIST FOUR FIELDS IN TABLE */

/* ALL MOVES OF THE POKEMON MUST BE UNIQUE.
THIS IS ENFORCED ON INSERTION INTO CURRENT
MOVES */